### ISSUE TITLE
problem installing autophot

### ISSUE THREAD

**Issue by FeliceCusano** [Astro-Sean/autophot#18]
Hi 

I am trying to install autophot in Ubuntu on WSL, but I get this error:
Collecting package metadata (current_repodata.json): done
Solving environment: |
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ Killed

I checked and I have  conda-forge and astropy in my channels.
Do you know which can be the problem?
thanks!
Felix

**Comment by Astro-Sean** [comment]
Hey Felix, 

Can I get an example of what you're entering in the terminal to install? Have you created a fresh conda enviroment?

- S

**Comment by FeliceCusano** [comment]
Hi Sean

thanks for your answer. 
I running the steps for the installation listed in the readme file, in details:
1) conda create -n autophot_env python=3.7
2) conda activate autophot_env
3) conda install -c astro-sean autophot

after point 3) I get this error
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ Killed

cheers, Felix

**Comment by jamesgillanders** [comment]
Hi Felix,

How long did you leave the "Solving environment:" to run before killing it? This process can take quite some time (up to ~10 minutes) to run (at least for me!). If it takes much longer than this, perhaps look at this (https://github.com/conda/conda/issues/8051#issuecomment-1407107812).

Specifically, try the following commands:

conda deactivate
conda update conda

making sure that the first command take you out of the root (base) directory.


Alternatively, you could try installing the package with mamba (https://mamba.readthedocs.io/en/latest/user_guide/mamba.html) instead of conda, using the following:

conda create -n autophot_env python=3.7 mamba=0.5
conda activate autophot_env
mamba install -c astro-sean autophot
